stages:
  - build
  - deploy

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

build:
  stage: build
  image: node:18-alpine
  script:
    - npm ci --cache .npm --prefer-offline
    - CI=false npm run build
  artifacts:
    paths:
      - build 

deploy:
  stage: deploy
  image: node:18-alpine
  script:
    - npx wrangler pages deploy ./build --project-name=nimoment --branch=main